services:
  postgres:
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: clinica
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
